name:                trimdent
version:             0.1.0.0
github:              "gregorias/trimdent"
license:             AGPL-3
author:              "Grzegorz Milka"
maintainer:          "grzegorzmilka@gmail.com"
copyright:           "Copyright (c) 2021 Grzegorz Milka"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gregorias/trimdent#readme>

# Some defaults recommended by https://kowainik.github.io/posts/2019-02-06-style-guide#default-extensions
# Also use Relude
default-extensions:
  BangPatterns
  DataKinds
  DeriveDataTypeable
  DeriveFoldable
  DeriveFunctor
  DeriveGeneric
  DeriveTraversable
  DerivingStrategies
  DerivingVia
  FlexibleContexts
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralisedNewtypeDeriving
  InstanceSigs
  LambdaCase
  MultiParamTypeClasses
  MultiWayIf
  NumericUnderscores
  OverloadedLabels
  OverloadedLists
  OverloadedStrings
  PatternSynonyms
  QuasiQuotes
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  TypeOperators
  UnicodeSyntax
  ViewPatterns

dependencies:
- base >= 4.13 && < 5

# no-type-defaults, this is dangerous, but in terms of convenience it's so
# useful to use ExtendedDefaultRules that I keep it.
ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Wmissing-deriving-strategies
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-type-defaults
  - -Wno-partial-type-signatures

library:
  source-dirs: src
  ghc-options:
  - -Wunused-packages

tests:
  trimdent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    - -Wunused-packages
    dependencies:
    - hspec
    - hspec-expectations-pretty-diff
    - trimdent
    - raw-strings-qq

  doctest:
    main:                DocTest.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is DocTest
    - -Wunused-packages
    dependencies:
    - doctest
